name: firebase
description: Firebase integrations for the infrastructure layer.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  analytics:
    path: ../../shared/analytics

  firebase_core: 4.4.0
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

  # Code Generation
  build_runner: any

  # DI Generator
  injectable_generator: any